site_name: 'Kitsaan ohjeet'
site_description: 'Ystävällinen kirjanpitäjä'
site_author: 'Arto Hyvättinen'
site_url: 'https://ohjeet.kitsas.fi'

copyright: 'Copyright &copy; 2017-2020 Arto Hyvättinen ja Kitsas Oy'
theme:
  name: null
  custom_dir: material
  palette:
    primary: 'deep purple'
    accent: 'deep purple'
  logo: 'img/Possu64.png'
  language: 'fi'
  favicon: 'img/Possu64.png'
  font: 'Roboto'
  mono: 'Ubuntu Mono'
  feature:
    tabs: false
  extra_templates:
    '404.html'
extra:
  disqus: 'kitsaan-ohjeet'
  social:
    - type: 'github'
      link: 'https://github.com/artoh/kitupiikki'
    - type: 'youtube'
      link: 'https://www.youtube.com/channel/UCVNHCMQoNb66OgzuTSfdKqQ'
    - type: 'twitter'
      link: 'https://twitter.com/kitsasfi'
    - type: 'facebook'
      link: 'https://facebook.com/kitsas.fi'
  search:
    language: 'fi'
markdown_extensions:
  - admonition
  - footnotes
  - meta
  - toc:
        permalink: true
pages:
  - Kitsas: 'index.md'
  - Kirjanpidosta lyhyesti: 'kirjanpito/index.md'
  - Aloittaminen:
    - Kitsaan pilvi: 'pilvi/index.md'
    - Uusi kirjanpito : 'aloitus/uusi/index.md'
    - Siirtäminen Kitupiikistä: 'aloitus/kitupiikki/index.md'
    - Ohjevideot : 'videot.md'
    - Pikanäppäimet : 'pika.md'
  - Kirjaaminen:
    - Kirjaaminen : 'kirjaus/index.md'
    - Menot ja tulot : 'kirjaus/menotulo/index.md'
    - Siirtotosite : 'kirjaus/siirto/index.md'
    - Tiliote : 'kirjaus/tiliote/index.md'
    - Palkka : 'kirjaus/palkka/index.md'
    - Tuonti: 'kirjaus/tuonti/index.md'
    - Muut tositteet: 'kirjaus/muu/index.md'
  - Selaaminen ja etsiminen: 'selaus/index.md'
  - Kierto:
    - Kierto: 'kierto/kierto/index.md'
    - Laskujen käsittely: 'kierto/laskut/index.md'
    - Määritykset: 'maaritykset/kierto/index.md'
    - Laskutusportaali: 'kierto/portaali/index.md'
  - Laskutus:
    - Myynnit: 'laskutus/myynnit/index.md'
    - Uusi lasku: 'laskutus/uusi/index.md'
    - Ennakkolasku: 'laskutus/ennakko/index.md'
    - Hyvityslasku: 'laskutus/hyvitys/index.md'
    - Maksumuistutukset: 'laskutus/muistutus/index.md'
    - Ryhmälasku : 'laskutus/ryhma/index.md'
    - Ostot: 'laskutus/ostot/index.md'
    - Rekisteri: 'laskutus/rekisteri/index.md'
    - Tuotteet: 'laskutus/tuotteet/index.md'
    - Vakioviitteet: 'laskutus/vakioviite/index.md'
  - Raportit: 'tulosteet/index.md'
  - Arvonlisävero:
    - Arvolisävero: 'alv/index.md'
    - Mallikirjaukset: 'alv/mallikirjaukset/index.md'
    - Alv-ilmoitus: 'alv/tilitys/index.md'
    - Korjaaminen: 'alv/korjaaminen/index.md'
    - Maksuperusteinen alv: 'alv/maksuperusteinen/index.md'
  - Tilikaudet ja tilinpäätös:
    - Tilikaudet : 'tilikaudet/index.md'
    - Sähköinen arkisto: 'tilikaudet/arkisto/index.md'
    - Budjetti: 'tilikaudet/budjetti/index.md'
    - Tilinpäätös:
        - Aloittaminen: 'tilinpaatos/aloittaminen/index.md'
        - Poistot: 'tilinpaatos/poistot/index.md'
        - Jaksotukset: 'tilinpaatos/jaksotukset/index.md'
        - Tulovero: 'tilinpaatos/tulovero/index.md'
        - Tilinpäätösasiakirja: 'tilinpaatos/asiakirja/index.md'
  - Asetukset:
    - Käyttöliittymä: 'maaritykset/kayttoliittyma/index.md'
    - Perusvalinnat: 'maaritykset/perusvalinnat/index.md'
    - Yhteystiedot: 'maaritykset/yhteystiedot/index.md'    
    - Liitteiden käsittely: 'maaritykset/liitteet/index.md'    
    - Käyttöoikeudet: 'maaritykset/kayttooikeudet/index.md'
    - Tililuettelo: 'maaritykset/tilikartta/index.md'
    - Kohdennukset: 'maaritykset/kohdennukset/index.md'
    - Tilinavaus : 'maaritykset/tilinavaus/index.md'
    - Laskutus: 'maaritykset/laskutus/index.md'
    - Oletustilit: 'maaritykset/oletustilit/index.md'
    - Maksutavat: 'maaritykset/maksutavat/index.md'
    - Tositesarjat: 'maaritykset/tositesarjat/index.md'
    - Sähköpostin lähettäminen: 'maaritykset/sahkoposti/index.md'
    - Laskujen kierto: 'maaritykset/kierto/index.md'
    - Verkkolasku: 'maaritykset/verkkolasku/index.md'
    - Kirjattavien kansio: 'maaritykset/inbox/index.md'
    - Verojen maksu: 'maaritykset/veronmaksu/index.md'
    - Palkkakirjaustilit: 'maaritykset/palkkatilit/index.md'
    - Raportit: 'maaritykset/raportit/index.md'
    - Tilinpäätöksen malli: 'maaritykset/tilinpaatos/index.md'
    - Tilikartan päivitys: 'maaritykset/paivitys/index.md'
  - Tuki: 'tuki.md'
  - Lisenssi: 'lisenssi.md'
extra_css:
  - 'stylesheets/extra.css'
