site_name: 'Kitsaan ohjeet'
site_description: 'Ystävällinen kirjanpitäjä'
site_author: 'Arto Hyvättinen'
site_url: 'https://ohjeet.kitsas.fi'

copyright: 'Copyright &copy; 2017-2020 Arto Hyvättinen ja Kitsas Oy'
theme:
  name: null
  custom_dir: material
  palette:
    primary: 'deep purple'
    accent: 'deep purple'
  logo: 'images/Possu64.png'
  language: 'fi'
  favicon: 'images/Possu64.png'
  font: 'Roboto'
  mono: 'Ubuntu Mono'
  feature:
    tabs: false
  extra_templates:
    '404.html'
extra:
  disqus: 'Kitupiikki'
  social:
    - type: 'github'
      link: 'https://github.com/artoh/kitupiikki'
    - type: 'youtube'
      link: 'https://www.youtube.com/channel/UCVNHCMQoNb66OgzuTSfdKqQ'
    - type: 'comment'
      link: 'http://palaute.kitupiikki.info'
    - type: 'twitter'
      link: 'https://twitter.com/KitupiikkiInfo'
  search:
    language: 'fi'
markdown_extensions:
  - admonition
  - footnotes
  - meta
  - toc:
        permalink: true
pages:
  - Kitsas: 'index.md'
  - Esittely:
    - Ominaisuudet: 'esittely.md'
    - Videot: 'videot.md'
    - Käyttöliittymä: 'ui.md'
    - Tuki: 'tuki.md'
    - Uutta kohti: 'v2/index.md'
  - Kirjanpidosta lyhyesti: 'kirjanpito/index.md'
  - Asennus: 'asennus.md'
  - Aloittaminen: 
    - Uusi kirjanpito : 'aloitus/uusi/index.md'
    - Siirtäminen Kitupiikistä: 'aloitus/kitupiikki/index.md'
  - Asetukset:
    - Perusvalinnat: 'maaritykset/perusvalinnat/index.md'
    - Tililuettelo: 'maaritykset/tilikartta/index.md'
    - Kohdennukset: 'maaritykset/kohdennukset/index.md'
    - Tilinavaus : 'maaritykset/tilinavaus/index.md'
    - Laskutus: 'maaritykset/laskutus/index.md'
    - Maksutavat: 'maaritykset/maksutavat/index.md'
    - Tositesarjat: 'maaritykset/tositesarjat/index.md'
    - Sähköpostin lähettäminen: 'maaritykset/sahkoposti/index.md'
    - Mukauttaminen:
        - Raportit: 'maaritykset/raportit/index.md'
        - Tilinpäätöksen malli: 'maaritykset/tilinpaatos/index.md'
        - Monimuotoiset tilikartat : 'maaritykset/monimuoto/index.md'
  - Kirjaaminen:
    - Kirjaaminen : 'kirjaus/kirjaaminen/index.md'
    - Menot ja tulot : 'kirjaus/menotulo/index.md'
    - Siirtotosite : 'kirjaus/siirto/index.md'
    - Tiliote : 'kirjaus/tiliote/index.md'
    - Palkka : 'kirjaus/palkka/index.md'
    - Muut tositteet: 'kirjaus/muu/index.md'
  - Selaaminen ja etsiminen: 'selaus/index.md'
  - Laskutus:
    - Laskutus: 'laskutus/index.md'
    - Uusi lasku: 'laskutus/uusi/index.md'
    - Maksumuistutukset: 'laskutus/muistutus/index.md'
    - Ryhmälasku : 'laskutus/ryhma/index.md'
  - Tulosteet: 'tulosteet/index.md'
  - Arvonlisävero:
    - Arvolisävero: 'alv/alv/index.md'
    - Mallikirjaukset: 'alv/mallikirjaukset/index.md'
    - Alv-ilmoitus: 'alv/tilitys/index.md'
    - Korjaaminen: 'alv/korjaaminen/index.md'
    - Maksuperusteinen alv: 'alv/maksuperusteinen/index.md'
  - Tilikaudet:
    - Tilikaudet : 'tilikaudet/tilikaudet/index.md'
    - Sähköinen arkisto: 'tilikaudet/arkisto/index.md'
    - Budjetti: 'tilikaudet/budjetti/index.md'
  - Tilinpäätös:
    - Aloittaminen: 'tilinpaatos/aloittaminen/index.md'
    - Poistot: 'tilinpaatos/poistot/index.md'
    - Jaksotukset: 'tilinpaatos/jaksotukset/index.md'
    - Tulovero: 'tilinpaatos/tulovero/index.md'
    - Tilinpäätösasiakirja: 'tilinpaatos/asiakirja/index.md'
  - Lisenssi: 'lisenssi.md'
extra_css:
  - 'stylesheets/extra.css'
